### ISSUE TITLE
请问usbc口接拓展坞能实现外接显示器嘛

### ISSUE THREAD

**Issue by JackesRrmhX** [JialeDeng/Razer-Blade15-2020-advandced-Hackintosh#1]
我这准备安装，想着提前了解下

**Comment by JialeDeng** [comment]
显示输出 包括HDMI、c口都是接到独显的，一般的拓展坞实现不了显示输出，如果需要的话 可以用带显卡芯片的USB转接头实现，或者去看看其他的DisplayLink方案也可以

**Comment by JackesRrmhX** [comment]
好的，感谢 那我还是整个nuc来黑果吧
